source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\generateOA.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\experimentDesignInteraction.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\convto.def.contr.subgr.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\wordlength.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\resolution.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\whole.resolution.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\evaluateOA.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\d.g.generator.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\minimumaberration.ranked.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\cleareffects.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\cleareffects.numbers.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\optimization.DOE.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\optimization.DOE.clear.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\max.p.generator.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\number.derived.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\runsize.prod.req.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\min.runsize.prod.req.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\resol.runsize.prod.req.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\OA.generation.2groups.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\OA.generation.3groups.R")
source("C:\\Users\\shilihui\\Desktop\\Webtrends codes\\OA.regular.generator.R")

options(mathdebug=TRUE)
